CREATE schema til_portfolio_projects.harvey_schema;
-----------------------------------------------------

CREATE TABLE til_portfolio_projects.harvey_schema.LEGO_COLORS (
	ID NUMBER(38,0),
	NAME VARCHAR(255),
	RGB VARCHAR(255),
	IS_TRANS VARCHAR(255)
);

INSERT INTO til_portfolio_projects.harvey_schema.LEGO_COLORS (
SELECT *
FROM  TIL_PORTFOLIO_PROJECTS.STAGING.LEGO_COLORS
);

ALTER TABLE lego_colors ADD PRIMARY KEY (ID);

-----------------------------------------------------

CREATE TABLE til_portfolio_projects.harvey_schema.LEGO_INVENTORIES (
	ID NUMBER(38,0),
	VERSION NUMBER(38,0),
	SET_NUM VARCHAR(255)
);

INSERT INTO til_portfolio_projects.harvey_schema.LEGO_INVENTORIES (
SELECT *
FROM  TIL_PORTFOLIO_PROJECTS.STAGING.LEGO_INVENTORIES
);

ALTER TABLE LEGO_INVENTORIES ADD PRIMARY KEY (ID);
ALTER TABLE LEGO_INVENTORIES ADD FOREIGN KEY (SET_NUM) REFERENCES LEGO_SETS(SET_NUM);
-----------------------------------------------------

create TABLE til_portfolio_projects.harvey_schema.LEGO_INVENTORY_PARTS (
	INVENTORY_ID NUMBER(38,0),
	PART_NUM VARCHAR(255),
	COLOR_ID NUMBER(38,0),
	QUANTITY NUMBER(38,0),
	IS_SPARE VARCHAR(255)
);

INSERT INTO til_portfolio_projects.harvey_schema.LEGO_INVENTORY_PARTS (
SELECT *
FROM  TIL_PORTFOLIO_PROJECTS.STAGING.LEGO_INVENTORY_PARTS
);

ALTER TABLE LEGO_INVENTORY_PARTS ADD FOREIGN KEY (COLOR_ID) REFERENCES LEGO_COLORS(ID);
ALTER TABLE LEGO_INVENTORY_PARTS ADD FOREIGN KEY (INVENTORY_ID) REFERENCES LEGO_INVENTORIES(ID);
ALTER TABLE LEGO_INVENTORY_PARTS ADD FOREIGN KEY (PART_NUM) REFERENCES LEGO_PARTS(PART_NUM);

ALTER TABLE LEGO_INVENTORY_PARTS ADD FOREIGN KEY (INVENTORY_ID) REFERENCES LEGO_INVENTORY_SETS2(ID);

-----------------------------------------------------


create or replace TABLE TIL_PORTFOLIO_PROJECTS.harvey_schema.LEGO_INVENTORY_SETS2 (
	INVENTORY_ID NUMBER(38,0),
	SET_NUM VARCHAR(255),
	QUANTITY NUMBER(38,0)
);

INSERT INTO til_portfolio_projects.harvey_schema.LEGO_INVENTORY_SETS2 (
SELECT *
FROM  TIL_PORTFOLIO_PROJECTS.STAGING.LEGO_INVENTORY_SETS
)
;
ALTER TABLE LEGO_INVENTORY_SETS2 ADD FOREIGN KEY (INVENTORY_ID) REFERENCES LEGO_INVENTORIES(ID);
ALTER TABLE LEGO_INVENTORY_SETS2 ADD FOREIGN KEY (SET_NUM) REFERENCES LEGO_SETS(SET_NUM);

-----------------------------------------------------

create TABLE til_portfolio_projects.harvey_schema.LEGO_PARTS (
	PART_NUM VARCHAR(255),
	NAME VARCHAR(255),
	PART_CAT_ID NUMBER(38,0)
);

INSERT INTO til_portfolio_projects.harvey_schema.LEGO_PARTS (
SELECT *
FROM  TIL_PORTFOLIO_PROJECTS.STAGING.LEGO_PARTS
);

ALTER TABLE LEGO_PARTS ADD FOREIGN KEY (PART_CAT_ID) REFERENCES LEGO_PART_CATEGORIES(ID);

-----------------------------------------------------

create TABLE til_portfolio_projects.harvey_schema.LEGO_PART_CATEGORIES (
	ID NUMBER(38,0),
	NAME VARCHAR(255)
);

INSERT INTO til_portfolio_projects.harvey_schema.LEGO_PART_CATEGORIES (
SELECT *
FROM  TIL_PORTFOLIO_PROJECTS.STAGING.LEGO_PART_CATEGORIES
);

ALTER TABLE LEGO_PART_CATEGORIES ADD PRIMARY KEY (ID);

-----------------------------------------------------

create TABLE til_portfolio_projects.harvey_schema.LEGO_SETS (
	SET_NUM VARCHAR(255),
	NAME VARCHAR(255),
	YEAR NUMBER(38,0),
	THEME_ID NUMBER(38,0),
	NUM_PARTS NUMBER(38,0)
);

INSERT INTO til_portfolio_projects.harvey_schema.LEGO_SETS (
SELECT *
FROM  TIL_PORTFOLIO_PROJECTS.STAGING.LEGO_SETS
);

ALTER TABLE LEGO_SETS ADD PRIMARY KEY (SET_NUM);
ALTER TABLE LEGO_SETS ADD FOREIGN KEY (THEME_ID) REFERENCES LEGO_THEMES(ID);

-----------------------------------------------------

create TABLE til_portfolio_projects.harvey_schema.LEGO_THEMES (
	ID NUMBER(38,0),
	NAME VARCHAR(255),
	PARENT_ID NUMBER(38,0)
);

INSERT INTO til_portfolio_projects.harvey_schema.LEGO_THEMES (
SELECT *
FROM  TIL_PORTFOLIO_PROJECTS.STAGING.LEGO_THEMES
);

ALTER TABLE LEGO_THEMES ADD PRIMARY KEY (ID);

-----------------------------------------------------